name: dd_tk_shop
description: 典典的小卖部v2版本

publish_to: 'none'

version: 1.1.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^3.25.4
  provider: ^4.3.3
  after_layout: ^1.0.7+2
  dio: ^3.0.10
  crypto: ^2.1.5
  encrypt: ^4.1.0
  flutter_swiper: ^1.1.6
  url_launcher: ^5.7.10
  flustars: ^0.3.3
  extended_image: ^1.5.0
  flutter_easyrefresh: ^2.1.8
  expandable_text: ^1.3.2
  shimmer: ^1.1.2
  ftoast: ^1.0.0
  get_storage: ^1.4.0
  dd_taoke_sdk: ^0.2.4
  waterfall_flow: 2.0.5
  flutter_spinkit: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/image/
  uses-material-design: true
